#!/bin/sh
# No loop, just one execution per line (mainly to adjust the various options accordingly).

brew update &>/dev/null
brew install zsh
brew install tmux
brew install git --with-pcre
brew install git-extras
brew install tig
brew install binutils
brew install coreutils
brew install proctools
brew install grc
brew install autojump
brew install bam
brew install htop-osx
brew install iftop
brew install irssi
brew install pidof
brew install pstree
brew install wget
brew install tree
brew install rename
brew install ngrep
brew install reattach-to-user-namespace
brew install watch
brew install nmap
brew install ascii

# ruby
brew install ruby --universal
`brew --prefix ruby`/bin/gem update --system
`brew --prefix ruby`/bin/gem update --no-rdoc --no-ri
brew install rbenv ruby-build

# vim
brew install vim --with-lua --with-python --with-ruby --without-perl --without-tcl --without-mzscheme
