#!/bin/sh
# No loop, just one execution per line (mainly to adjust the various options accordingly).

brew update &>/dev/null
brew install tmux
brew install git --with-pcre
brew install git-extras
brew install tig
brew install binutils
brew install proctools
brew install grc
brew install autojump
brew install bam
brew install htop-osx
brew install iftop
brew install irssi
brew install midnight-commander
brew install pidof
brew install pstree
brew install pngquant
brew install wget
brew install tree
brew install spark
brew install sshfs
brew install rename
brew install ngrep
brew install reattach-to-user-namespace

# python
brew install readline sqlite gdbm --universal
brew install python --universal --framework
`brew --prefix python`/bin/easy_install pip
`brew --prefix python`/bin/pip install --upgrade distribute
`brew --prefix python`/bin/pip install virtualenv
`brew --prefix python`/bin/pip install virtualenvwrapper

# ruby
brew install ruby --universal
`brew --prefix ruby`/bin/gem update --system
`brew --prefix ruby`/bin/gem update --no-rdoc --no-ri

# vim
brew install vim --with-lua --with-python --with-ruby --without-perl --without-tcl --without-mzscheme

